# Numpy

In [2]:
import numpy as np # numpy array store values of same data type

In [21]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [22]:
arr # this would be a 1-dimensional array - the easy way to check it is to count the number of brackets at the start or the end

array([1, 2, 3, 4, 5])

In [23]:
type(arr)

numpy.ndarray

In [25]:
arr.shape

(5,)

In [42]:
# Multinested array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr = np.array([my_list1, my_list2, my_list3])

In [30]:
arr # this would be a 2-d array

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [31]:
arr.shape

(3, 5)

In [32]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [45]:
arr.reshape(1,15) # this would still be a 2-d array as it contains 2 brackets at the start and 2 brackets at the end

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [46]:
my_arr = np.array([1,2,3,4,5,6,7,8,9])

In [47]:
my_arr[3]

4

In [48]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [49]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [54]:
# to get first two elements of the first two rows and first two elements of the first two columns - [[1, 2],
#                                                                                                    [2, 3]]
arr[0:2,0:2] # or arr[:2,:2]

array([[1, 2],
       [2, 3]])

In [55]:
arr[0:2,:] # first two rows and all columns

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [56]:
# to get last two elements of the last two rows and last two elements of the last two columns - [[5, 6],
#                                                                                                [8, 9]]
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [60]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr = np.arange(0,10,step=2) # default step is 1
arr

array([0, 2, 4, 6, 8])

In [62]:
np.linspace(1, 5, 20) # returns evenly spaced numbers over a specified interval

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [63]:
my_arr = np.array([1,2,3,4,5,6,7,8,9])

In [65]:
my_arr[3:] = 100
my_arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [68]:
arr1 = my_arr.copy() # performs copy whereas arr1=arr will copy the reference
arr1 # changes made in arr1 will not change my_arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [70]:
arr1 = my_arr.copy()
arr1[3:] = 500
print(my_arr)
print(arr1)

[  1   2   3 100 100 100 100 100 100]
[  1   2   3 500 500 500 500 500 500]


In [71]:
arr1 = my_arr
arr1[3:] = 500
print(my_arr)
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [76]:
val = 3
print(my_arr)
print(my_arr < val)
print(my_arr[my_arr< val]) # will print all elements that are less than val
print(my_arr*val)

[  1   2   3 500 500 500 500 500 500]
[ True  True False False False False False False False]
[1 2]
[   3    6    9 1500 1500 1500 1500 1500 1500]


In [78]:
print(np.ones(4))
print(np.ones(4, dtype=float))
print(np.ones(4, dtype=int))

[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1 1 1 1]


In [81]:
np.ones((2,5), dtype=float) # creates a 2-d array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
np.random.rand(3,3) # returns random samples from a uniform distribution over [0, 1)

array([[0.21325613, 0.0508473 , 0.986271  ],
       [0.70798082, 0.10066416, 0.57955731],
       [0.87265197, 0.18939559, 0.54116395]])

In [83]:
np.random.randn(3,3) # returns random samples from the standard normal distribution

array([[ 0.35325816, -0.51080236,  0.39935204],
       [ 1.17299113,  0.13831817,  0.57430718],
       [ 0.4492227 ,  0.40137105,  0.34679555]])

In [84]:
np.random.randint(0,100,8) # select 8 numbers between 0 and 100

array([23, 97, 91,  8, 21, 20, 33, 32])

In [85]:
np.random.randint(0,100,8).reshape(2,4)

array([[44, 39, 34,  9],
       [76, 15, 36, 39]])

In [86]:
np.random.random_sample((1,5)) # Return random floats in the half-open interval [0.0, 1.0)

array([[0.8105503 , 0.53693783, 0.53420177, 0.3682323 , 0.05391635]])